# -*- coding: utf-8 -*-
"""Exa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h_OreOS5vf5QiDcjbEsyOkvnS_BkqoGQ

Alumna: Alondra Vianey Verástegui Peña

Materia: Protección de datos

Carrera: Licenciatura en Ciencia de datos

Semestre: 7°

1.
"""

def serca_Prime (n):
  if not Primo(n): return False
  i = 0
  while True:
    i += 1
    if Primo(n+i): return n+i

"""2."""

def Primo(n):
  if n < 2: return False
  for i in range(2,int(n/2)+1):
    if n % i == 0: return False
  return True

"""3."""

def median(datos):
    mitad = len(datos) // 2
    datos.sort()
    return datos[mitad]

"""4."""

import random

def contra():
  contrasena = ""
  for i in range(1,random.randrange(7,10)):
    contrasena += chr(random.randrange(33,126,1))
  return contrasena

"""5."""

def hipo (a,b):
  return (a**2+b**2)**0.5

!git clone https://github.com/Aloverastegui/AV.git
import sys
sys.path.append('/content/AV')

from exa import *